--Idea
--Domain
--Why that Domain?
--Dataset
--Options what all options for dataset
--Why this dataset only ??
--Dataset LINK
--Properties of the dataset using for the project 
--End consumer
--Why End consumer ?
-- Prospective Finalilize 
-- Why you want to follow that Prospective?? 

==============================================================================================================================
											PROJECT PHASE 1

/* ============================================================
   CHOC SALES PROJECT
   PHASE 1 — KPI ANALYSIS
   Perspective: Sales Performance & Revenue Optimization
   End Consumer: Sales Manager

   Dataset:Choc Sales Dataset
   Columns:
   Sales Person
   Country
   Product
   Date
   Amount
   Boxes Shipped
   ============================================================ */


/* ============================================================
   KPI 01 — TOTAL REVENUE
   ============================================================

   How much total revenue has the company generated from all
   chocolate sales?
*/

SELECT
    SUM(Amount) AS Total_Revenue
FROM ChocSales;


/* ============================================================
   KPI 02 — TOTAL BOXES SHIPPED
   ============================================================

   Calculate the total number of boxes shipped across all
   transactions.

*/

SELECT
    SUM(Boxes_Shipped) AS Total_Boxes_Shipped
FROM ChocSales;


/* ============================================================
   KPI 03 — TOTAL SALES TRANSACTIONS
   ============================================================
   How many individual sales transactions were completed?

*/

SELECT
    COUNT(*) AS Total_Transactions
FROM ChocSales;


/* ============================================================
   KPI 04 — AVERAGE TRANSACTION VALUE
   ============================================================

   What is the average revenue generated from a single
   chocolate sales transaction?
*/

SELECT
    AVG(Amount) AS Average_Revenue
FROM ChocSales;


/* ============================================================
   KPI 05 — AVERAGE BOXES PER TRANSACTION
   ============================================================

   On average, how many chocolate boxes are shipped in each
   sales transaction?
*/

SELECT
    AVG(Boxes_Shipped) AS Average_Boxes_Per_Transaction
FROM ChocSales;


/* ============================================================
   KPI 06 — REVENUE PER BOX
   ============================================================

   Divide total revenue by total boxes shipped.
*/

SELECT
    SUM(Amount) / (SUM(Boxes_Shipped))
        AS Revenue_Per_Box
FROM ChocSales;


/* ============================================================
   KPI 07 — HIGHEST TRANSACTION VALUE
   ============================================================

   What is the highest-value chocolate sale recorded?
*/

SELECT
    MAX(Amount) AS Highest_Transaction_Value
FROM ChocSales;


/* ============================================================
   KPI 08 — LOWEST TRANSACTION VALUE
   ============================================================

   What is the lowest-value chocolate sale recorded?

*/

SELECT
    MIN(Amount) AS Lowest_Transaction_Value
FROM ChocSales;


/* ============================================================
   KPI 09 — NUMBER OF SALESPEOPLE
   ============================================================

   How many unique salespeople are currently represented
   in the sales data?

*/

SELECT
    COUNT(DISTINCT Sales_Person) AS Total_Salespeople
FROM ChocSales;


/* ============================================================
   KPI 10 — NUMBER OF COUNTRIES
   ============================================================

   How many different countries are contributing to chocolate
   sales?

*/

SELECT
    COUNT(DISTINCT Country) AS Total_Countries
FROM ChocSales;


/* ============================================================
   KPI 11 — NUMBER OF PRODUCTS
   ============================================================

   How many different chocolate products are being sold?

*/

SELECT
    COUNT(DISTINCT Product) AS Total_Products
FROM chocsales;


/* ============================================================
   KPI 12 — TOP SALESPERSON REVENUE
   ============================================================

   What is the highest total revenue generated by any
   individual salesperson?

*/

With T1 AS(
Select Sales_Person,Sum([Amount]) As [Total_Sales]
From ChocSales
Group by Sales_Person
)
Select *
From T1
Where [Total_Sales] = ( Select Max([Total_Sales])
From T1);



/* ============================================================
   KPI 13 — TOP PRODUCT REVENUE
   ============================================================
   What is the highest total revenue generated by a single
   chocolate product?

*/
With T1 As (
Select 
[Product],Sum([Amount]) As [Total_Product]
From ChocSales
Group by [Product]
)
Select * From T1
Where [Total_Product] = (Select Max([Total_Product]) From T1);


/* ============================================================
   KPI 14 — TOP COUNTRY REVENUE
   ============================================================
   What is the highest revenue generated by any individual
   country?

*/
With T1 AS (
Select 
        [Country],Sum([Amount]) AS [Total_Revenue]
        From ChocSales
        Group by [Country]
        )
Select *
    From T1
    Where [Total_Revenue] = ( Select 
                                    Max([Total_Revenue])
                                    From T1);


/* ============================================================
   KPI 15 — TOP COUNTRY REVENUE CONTRIBUTION %
   ============================================================
   What percentage of the company's total revenue comes from
   the highest-performing country?

   
*/
With T1 AS(
Select [Country],Sum([Amount]) AS [Total_Revenue]
From ChocSales
Group by [Country]
)
Select *,
 [Total_Revenue] *100.0 / (Select Sum([Total_Revenue])From T1) AS [Percentage]
From T1 

======================================================================================================================
											PROJECT PHASE - 2

/* ============================================================
   CHOC SALES PROJECT
   PHASE 2 — UNIVARIATE ANALYSIS
   Perspective: Sales Performance & Revenue Optimization
   End Consumer: Sales Manager

   Dataset: ChocSales

   Columns:
   Sales_Person
   Country
   Product
   Date
   Amount
   Boxes_Shipped
   ============================================================ */


/* ============================================================
   ANALYSIS 01 — REVENUE BY SALESPERSON
   ============================================================

   Calculate total revenue generated by each salesperson.

*/

SELECT
    Sales_Person,
    SUM(Amount) AS Total_Revenue
FROM ChocSales
GROUP BY Sales_Person
ORDER BY Total_Revenue DESC;


/* ============================================================
   ANALYSIS 02 — TRANSACTIONS BY SALESPERSON
   ============================================================

   Count the number of transactions for every salesperson.
*/

SELECT
    Sales_Person,
    COUNT(*) AS Total_Transactions
FROM ChocSales
GROUP BY Sales_Person
ORDER BY Total_Transactions DESC;


/* ============================================================
   ANALYSIS 03 — BOXES SHIPPED BY SALESPERSON
   ============================================================

   Calculate total boxes shipped by each salesperson.

*/

SELECT
    Sales_Person,
    SUM(Boxes_Shipped) AS Total_Boxes_Shipped
FROM ChocSales
GROUP BY Sales_Person
ORDER BY Total_Boxes_Shipped DESC;


/* ============================================================
   ANALYSIS 04 — REVENUE BY COUNTRY
   ============================================================

   Calculate total revenue generated by each country.

*/

SELECT
    Country,
    SUM(Amount) AS Total_Revenue
FROM ChocSales
GROUP BY Country
ORDER BY Total_Revenue DESC;
        

/* ============================================================
   ANALYSIS 05 — TRANSACTIONS BY COUNTRY
   ============================================================

   Which countries have the highest number of sales
   transactions?

*/

SELECT
    Country,
    COUNT(*) AS Total_Transactions
FROM ChocSales
GROUP BY Country
ORDER BY Total_Transactions DESC;


/* ============================================================
   ANALYSIS 06 — BOXES SHIPPED BY COUNTRY
   ============================================================

   Calculate total boxes shipped for each country.

*/

SELECT
    Country,
    SUM(Boxes_Shipped) AS Total_Boxes_Shipped
FROM ChocSales
GROUP BY Country
ORDER BY Total_Boxes_Shipped DESC;


/* ============================================================
   ANALYSIS 07 — REVENUE BY PRODUCT
   ============================================================

   Calculate total revenue generated by every product.

*/

SELECT
    Product,
    SUM(Amount) AS Total_Revenue
FROM ChocSales
GROUP BY Product
ORDER BY Total_Revenue DESC;


/* ============================================================
   ANALYSIS 08 — TRANSACTIONS BY PRODUCT
   ============================================================

   Count the number of transactions associated with each
   product.

*/

SELECT
    Product,
    COUNT(*) AS Total_Transactions
FROM ChocSales
GROUP BY Product
ORDER BY Total_Transactions DESC;


/* ============================================================
   ANALYSIS 09 — BOXES SHIPPED BY PRODUCT
   ============================================================

   Calculate total boxes shipped for each product.

*/

SELECT
    Product,
    SUM(Boxes_Shipped) AS Total_Boxes_Shipped
FROM ChocSales
GROUP BY Product
ORDER BY Total_Boxes_Shipped DESC;


/* ============================================================
   ANALYSIS 10 — MONTHLY REVENUE
   ============================================================

   Extract the month from Date and calculate total revenue
   for each month.

*/

SELECT
    MONTH(Date) AS Sales_Month,
    SUM(Amount) AS Total_Revenue
FROM ChocSales
GROUP BY MONTH(Date)
ORDER BY Sales_Month;


/* ============================================================
   ANALYSIS 11 — MONTHLY TRANSACTION VOLUME
   ============================================================

   Which months have the highest number of sales transactions?

*/

SELECT
    MONTH(Date) AS Sales_Month,
    COUNT(*) AS Total_Transactions
FROM ChocSales
GROUP BY MONTH(Date)
ORDER BY Sales_Month;


/* ============================================================
   ANALYSIS 12 — MONTHLY BOXES SHIPPED
   ============================================================

   Which months have the highest sales volume in terms of
   boxes shipped?
   
*/

SELECT
    MONTH(Date) AS Sales_Month,
    SUM(Boxes_Shipped) AS Total_Boxes_Shipped
FROM ChocSales
GROUP BY MONTH(Date)
ORDER BY Sales_Month;


/* ============================================================
   ANALYSIS 13 — QUARTERLY REVENUE
   ============================================================

   Which quarter generated the highest revenue?

*/

Select 
        DATEPART(QUARTER,date) As [Sales_Quater],
        Sum(Amount) AS Total_Revenue
        From ChocSales
        Group by DATEPART(QUARTER,date)
        order by Sales_Quater


/* ============================================================
   ANALYSIS 14 — TRANSACTION VALUE DISTRIBUTION
   ============================================================

   How are individual sales transaction values distributed?
   Are most transactions small, medium, or high value?
   
*/

WITH T1 AS (
    SELECT 
        Amount,
        CASE 
            WHEN Amount < 5000 THEN 'Below 5K'
            WHEN Amount < 10000 THEN '5K - 10K'
            WHEN Amount < 15000 THEN '10K - 15K'
            ELSE '15K+'
        END AS Revenue_Band
    FROM ChocSales
)
SELECT 
    Revenue_Band,
    COUNT(*) AS Total_Transactions
FROM T1
GROUP BY Revenue_Band
ORDER BY Total_Transactions DESC;
 


/* ============================================================
   ANALYSIS 15 — BOXES SHIPPED DISTRIBUTION
   ============================================================

   What proportion of transactions are low-volume,
   medium-volume, or high-volume shipments?
  
*/
 
 WITH T1 AS (
    SELECT
        Boxes_Shipped,
        CASE
            WHEN Boxes_Shipped < 100 THEN 'Below 100 Boxes'
            WHEN Boxes_Shipped < 250 THEN '100 - 249 Boxes'
            WHEN Boxes_Shipped < 400 THEN '250 - 399 Boxes'
            ELSE '400+ Boxes'
        END AS Box_Volume_Band
    FROM ChocSales
)
SELECT
    Box_Volume_Band,
    COUNT(*) AS Total_Transactions
FROM T1
GROUP BY Box_Volume_Band
ORDER BY Total_Transactions DESC;

======================================================================================================================
										PROJECT PHASE-3
	
	/* ============================================================
   CHOCSALES PROJECT
   PHASE 3 — BIVARIATE ANALYSIS
   Perspective:Sales Performance & Revenue Optimization Analysis
   End Consumer:Sales Manager

   Dataset: ChocSales
   
   Columns:
   Sales_Person
   Country
   Product
   Date
   Amount
   Boxes_Shipped
   ============================================================ */


/* ============================================================
   ANALYSIS 01 — TRANSACTION VALUE vs BOX VOLUME
   ============================================================

   Calculate the average transaction Amount for different
   Boxes Shipped volume bands.

*/
    With T1 AS(
    Select 
    Boxes_Shipped,Amount,
    Case
        When  Boxes_Shipped < 100 Then 'Low Volume'
        When  Boxes_Shipped < 250 Then 'Medium Volume'
        When  Boxes_Shipped < 400 Then 'High Volume'
    Else 'Very High Volume' 
   End  AS Shipment_volume_bands
    From ChocSales
    )
    Select 
    Shipment_volume_bands,
    Count(*) AS Transactions,
    Avg(Amount) AS Avg_Transaction_Value
    From T1 
    Group by Shipment_volume_bands
    order by Avg_Transaction_Value Desc



/* ============================================================
   ANALYSIS 02 — REVENUE BAND vs BOX VOLUME
   ============================================================

   Categorize transactions by revenue band and calculate
   their average boxes shipped.

*/
       With T1 AS (
       Select 
                Amount,Boxes_Shipped,
                Case 
                    When Amount < 5000 Then 'Below 5k'
                    When Amount < 10000 Then '5k-10k'
                    When Amount < 15000 Then '10k - 15k'
                Else '15k+'
            End AS revenue_Band
            From  ChocSales
            )
            Select 
                revenue_Band,
                COUNT(*) AS Transactions,
                Avg(Boxes_Shipped) AS Avg_Boxes_Shippped 
                From T1
                Group by revenue_Band
                Order by Transactions



/* ============================================================
   ANALYSIS 03 — SALESPERSON vs PRODUCT MIX
   ============================================================

   How many different chocolate products does each salesperson
   actively sell?

*/

SELECT
    Sales_Person,
    COUNT(DISTINCT Product) AS Unique_Products_Sold
FROM ChocSales
GROUP BY Sales_Person
ORDER BY Unique_Products_Sold DESC;


/* ============================================================
   ANALYSIS 04 — SALESPERSON vs MARKET REACH
   ============================================================
   Count the distinct countries associated with each
   salesperson.

*/

SELECT
    Sales_Person,
    COUNT(DISTINCT Country) AS Countries_Served
FROM ChocSales
GROUP BY Sales_Person
ORDER BY Countries_Served DESC;


/* ============================================================
   ANALYSIS 05 — PRODUCT vs MARKET REACH
   ============================================================

   Count the number of distinct countries in which each
   product is sold.

*/

Select Product,
       Count(Distinct Country) AS Country_Served
       From ChocSales
       Group by Product
       order by Country_Served Desc
    


/* ============================================================
   ANALYSIS 06 — SALESPERSON vs PRODUCT DIVERSITY
   ============================================================

   Calculate the ratio of unique products handled to
   total transactions for each salesperson.

*/

    With T1 As (
    Select 
        Sales_person,
        Count(Distinct Product) AS Unique_Products,
        count(*) As Total_Transactions
        From ChocSales
        Group by Sales_Person 
        )
        Select 
            Sales_Person,
            Unique_Products,
            Total_Transactions,
            Round(
                    Unique_Products * 1.0 /  Total_Transactions,3)
                    As Product_Diversity_Ratio
                    From T1
                    Order by Product_Diversity_Ratio Desc


/* ============================================================
   ANALYSIS 07 — COUNTRY vs PRODUCT DIVERSITY
   ============================================================

   Count distinct products available in each country.

*/
  SELECT
    Country,
    COUNT(DISTINCT Product) AS Unique_Products_Available
FROM ChocSales
GROUP BY Country
ORDER BY Unique_Products_Available DESC;
     
        


/* ============================================================
   ANALYSIS 08 — COUNTRY vs SALESPERSON COVERAGE
   ===========================================================

   Technical Question:
   Count the number of unique salespeople operating in
   each country.

*/

SELECT
    Country,
    COUNT(DISTINCT Sales_Person) AS Salespeople_Covering_Market
FROM ChocSales
GROUP BY Country
ORDER BY Salespeople_Covering_Market DESC;


/* ============================================================
   ANALYSIS 09 — PRODUCT vs SALESPERSON COVERAGE
   ============================================================

   Count distinct salespeople associated with each product.

*/

SELECT
    Product,
    COUNT(DISTINCT Sales_Person) AS Salespeople_Selling_Product
FROM ChocSales
GROUP BY Product
ORDER BY Salespeople_Selling_Product DESC;


/* ============================================================
   ANALYSIS 10 — PRODUCT vs AVERAGE BOXES PER TRANSACTION
   ============================================================

   Calculate average boxes shipped per transaction for each
   product.

*/

   SELECT
    Product,
    COUNT(*) AS Transactions,
    AVG(Boxes_Shipped) AS Avg_Boxes_Per_Transaction
    FROM ChocSales
    GROUP BY Product
    ORDER BY Avg_Boxes_Per_Transaction DESC;


/* ============================================================
   ANALYSIS 11 — COUNTRY vs AVERAGE BOXES PER TRANSACTION
   ============================================================

   Calculate the average number of boxes shipped per
   transaction for each country.

*/

SELECT
    Country,
    COUNT(*) AS Transactions,
    AVG(Boxes_Shipped) AS Avg_Boxes_Per_Transaction
FROM ChocSales
GROUP BY Country
ORDER BY Avg_Boxes_Per_Transaction DESC;


/* ============================================================
   ANALYSIS 12 — SALESPERSON vs AVERAGE BOXES PER TRANSACTION
   ============================================================

   Calculate average boxes shipped per transaction for
   every salesperson.

*/

SELECT
    Sales_Person,
    COUNT(*) AS Transactions,
    AVG(Boxes_Shipped) AS Avg_Boxes_Per_Transaction
FROM ChocSales
GROUP BY Sales_Person
ORDER BY Avg_Boxes_Per_Transaction DESC;


/* ============================================================
   ANALYSIS 13 — PRODUCT vs TRANSACTION VALUE BAND
   ============================================================

   Categorize transactions into revenue bands for each
   product and count transactions in each band.

*/
        WITH T1 AS (
    SELECT
        Product,
        CASE
            WHEN Amount < 5000 THEN 'Below 5K'
            WHEN Amount < 10000 THEN '5K - 10K'
            WHEN Amount < 15000 THEN '10K - 15K'
            ELSE '15K+'
        END AS Revenue_Band
    FROM ChocSales
)
SELECT
    Product,
    Revenue_Band,
    COUNT(*) AS Transaction_Count
FROM T1
GROUP BY
    Product,
    Revenue_Band
ORDER BY
    Product,
    Transaction_Count DESC;
      



/* ============================================================
   ANALYSIS 14 — SALESPERSON vs TRANSACTION VALUE BAND
   ============================================================

   Categorize each transaction by Amount and compare the
   number of transactions generated by each salesperson
   within each revenue band.

*/
                WITH T1 AS (
    SELECT
        Sales_Person,
        CASE
            WHEN Amount < 5000 THEN 'Below 5K'
            WHEN Amount < 10000 THEN '5K - 10K'
            WHEN Amount < 15000 THEN '10K - 15K'
            ELSE '15K+'
        END AS Revenue_Band
    FROM ChocSales
)

SELECT
    Sales_Person,
    Revenue_Band,
    COUNT(*) AS Transactions
FROM T1
GROUP BY
    Sales_Person,
    Revenue_Band
ORDER BY
    Sales_Person,
    Transactions DESC;
            

/* ============================================================
   ANALYSIS 15 — COUNTRY vs TRANSACTION VALUE BAND
   ============================================================

   Technical Question:
   Categorize transactions into revenue bands and compare
   transaction distribution across countries.

 
*/
           WITH T1 AS (
    SELECT
        Country,
        CASE
            WHEN Amount < 5000 THEN 'Below 5K'
            WHEN Amount < 10000 THEN '5K - 10K'
            WHEN Amount < 15000 THEN '10K - 15K'
            ELSE '15K+'
        END AS Revenue_Band
    FROM ChocSales
)

SELECT
    Country,
    Revenue_Band,
    COUNT(*) AS Transactions
FROM T1
GROUP BY
    Country,
    Revenue_Band
ORDER BY
    Country,
    Transactions DESC; 
 
 ======================================================================================================================
											PROJECT PHASE - 4  
		
	/* ============================================================
   CHOCSALES PROJECT
   PHASE 4 — MULTIVARIATE ANALYSIS
   Perspective: Sales Performance & Revenue Optimization Analysis
   End Consumer: Sales Manager
   Objective: Analyze THREE OR MORE variables simultaneously to identify
   deeper sales patterns, performance drivers, opportunities,
   and revenue optimization areas.

   Dataset:ChocSales

   Columns:
   Sales_Person
   Country
   Product
   Date
   Amount
   Boxes_Shipped

   ============================================================ */

/* ============================================================
   ANALYSIS 01 — TOP SALESPERSON IN EACH COUNTRY
   ============================================================


   Calculate salesperson revenue within each country and
   rank salespeople within their respective country.

*/
      WITH T1 AS (
    SELECT
        Sales_Person,
        Country,
        SUM(Amount) AS Total_Revenue,
        ROW_NUMBER() OVER (
            PARTITION BY Country
            ORDER BY SUM(Amount) DESC
        ) AS Ranking
    FROM ChocSales
    GROUP BY
        Sales_Person,
        Country
)

SELECT *
FROM T1
WHERE Ranking = 1
ORDER BY Total_Revenue DESC;
        
      
/* ============================================================
   ANALYSIS 02 — TOP 3 SALESPERSONS IN EACH COUNTRY
   ============================================================

   Rank salespeople within each country and return the
   three highest revenue generators.

  
*/

 WITH T1 AS (
    SELECT
        Sales_Person,
        Country,
        SUM(Amount) AS Total_Revenue,
        Row_Number() OVER (
            PARTITION BY Country
            ORDER BY SUM(Amount) DESC
        ) AS Ranking
    FROM ChocSales
    GROUP BY
        Sales_Person,
        Country
)

SELECT *
FROM T1
WHERE Ranking <= 3
ORDER BY Total_Revenue DESC;


/* ============================================================
   ANALYSIS 03 — TOP PRODUCT FOR EACH COUNTRY
   ============================================================

   Calculate product revenue by country and identify the
   highest-performing product within every market.

*/

 WITH T1 AS (
    SELECT
        [Product],
        Country,
        SUM(Amount) AS Total_Revenue,
        ROW_NUMBER() OVER (
            PARTITION BY Country
            ORDER BY SUM(Amount) DESC
        ) AS Ranking
    FROM ChocSales
    GROUP BY
        [Product],
        Country
)

SELECT *
FROM T1
WHERE Ranking = 1
ORDER BY Total_Revenue DESC;


/* ============================================================
   ANALYSIS 04 — TOP 3 PRODUCTS FOR EACH COUNTRY
   ============================================================

   Rank products based on revenue within each country.

*/

 WITH T1 AS (
    SELECT
        Product,
        Country,
        SUM(Amount) AS Total_Revenue,
        Row_Number() OVER (
            PARTITION BY Country
            ORDER BY SUM(Amount) DESC
        ) AS Ranking
    FROM ChocSales
    GROUP BY
        Product,Country
        
)

SELECT *
FROM T1
WHERE Ranking <= 3
ORDER BY
    Country,Ranking
   

/* ============================================================
   ANALYSIS 05 — SALESPERSON + PRODUCT PERFORMANCE
   ============================================================

   Calculate revenue for each salesperson-product combination
   and rank the combinations.

*/

    With T1 As(
    Select 
        Sales_Person,
        Product,
        Sum([Amount]) AS Total_revenue,
        Row_Number () Over ( 
                            
                            Order by Sum([Amount])Desc ) AS Ranks
        From ChocSales
    Group by  Sales_Person,
        Product 
        )
        Select *
        From T1 
        Where Ranks <= 10
        Order by Ranks 
       
/* ============================================================
   ANALYSIS 06 — SALESPERSON + PRODUCT + REVENUE PER BOX
   ============================================================

   Calculate revenue per box for every salesperson-product
   combination.
 
*/

WITH T1 AS (
    SELECT
        Sales_Person,
        Product,
        SUM(Amount) AS Total_Revenue,
        SUM(Boxes_Shipped) AS Total_Boxes
    FROM ChocSales
    GROUP BY
        Sales_Person,
        Product
)

SELECT
    *,
    Total_Revenue * 1.0 / Total_Boxes  AS Revenue_Per_Box
FROM T1
ORDER BY Revenue_Per_Box DESC;


/* ============================================================
   ANALYSIS 07 — COUNTRY + PRODUCT + REVENUE CONTRIBUTION
   ============================================================

   Calculate product revenue within each country and determine
   its percentage contribution to that country's total revenue.

*/
     WITH T1 AS (
    SELECT
        Product,
        Country,
        SUM(Amount) AS Product_Revenue,
        SUM(SUM(Amount)) OVER (
            PARTITION BY Country
        ) AS Country_Revenue
    FROM ChocSales
    GROUP BY
        Product,
        Country
)

SELECT
    Product,
    Country,
    Product_Revenue,
    Product_Revenue * 100.0 / Country_Revenue AS Contribution_Percent
FROM T1
ORDER BY Contribution_Percent DESC;


/* ============================================================
   ANALYSIS 08 — SALESPERSON + COUNTRY + REVENUE CONTRIBUTION
   ============================================================

   Calculate salesperson revenue within each country and
   determine each salesperson's contribution to that market.

  
*/


  WITH T1 AS (
    SELECT
        Sales_Person,
        Country,
        SUM([Amount]) AS [Sales_Person_Revenue],
        SUM(SUM([Amount])) OVER (
            PARTITION BY Country
        ) AS [Country_Revenue]
    FROM ChocSales
    GROUP BY
        Sales_Person,
        Country
)

SELECT
    Sales_Person,
    Country,
    [Sales_Person_Revenue],
    [Country_Revenue],
    [Sales_Person_Revenue] * 100.0
        / [Country_Revenue] AS [Sales_Person_Contri]
FROM T1
ORDER BY
    [Sales_Person_Contri] DESC;
        


/* ============================================================
   ANALYSIS 09 — MONTH + COUNTRY + REVENUE
   ============================================================

   Calculate monthly revenue for each country and identify
   monthly market performance.

*/

SELECT
    MONTH(Date) AS Sales_Month,
    Country,
    SUM(Amount) AS Total_Revenue
FROM ChocSales
GROUP BY
    MONTH(Date),
    Country
ORDER BY
    Sales_Month,
    Total_Revenue DESC;


/* ============================================================
   ANALYSIS 10 — MONTH + PRODUCT + REVENUE
   ============================================================

   Calculate monthly revenue for every product.

*/

     SELECT
    MONTH(Date) AS Sales_Month,
    Product,
    SUM(Amount) AS Total_Revenue
FROM ChocSales
GROUP BY
    MONTH(Date),
    Product
ORDER BY
    Sales_Month,
    Total_Revenue DESC;


/* ============================================================
   ANALYSIS 11 — MONTH-OVER-MONTH REVENUE GROWTH
   ============================================================

   Calculate monthly revenue and compare it with the previous
   month's revenue.


*/
      WITH T1 AS (
    SELECT
        MONTH([Date]) AS [Sales_Month],
        SUM([Amount]) AS [Total_Sales],
        LAG(SUM([Amount])) OVER (
            ORDER BY MONTH([Date])
        ) AS [Last_Sale]
    FROM [DB1].[dbo].[ChocSales]
    GROUP BY
        MONTH([Date])
)

SELECT
    *,
    [Total_Sales] - [Last_Sale] AS [Sales_Difference]
FROM T1;
           
/* ============================================================
   ANALYSIS 12 — COUNTRY + MONTH-OVER-MONTH GROWTH
   ============================================================

   Calculate monthly revenue for each country and compare
   each month's revenue with the previous month within
   the same country.

*/
       WITH T1 AS (
    SELECT
        Country,
        MONTH(Date) AS [Sales_Month],
        SUM(Amount) AS [Total_Sales],
        LAG(SUM(Amount)) OVER (
                PARTITION BY Country
                ORDER BY MONTH(Date)
        ) AS [Previous_Month_Revenue]
    FROM ChocSales
    GROUP BY
        Country,
        MONTH(Date)
)

SELECT *,
           
    ([Total_Sales] - [Previous_Month_Revenue]) * 100.0
        / [Previous_Month_Revenue] AS [MOM_Growth_Percent]
FROM T1
ORDER BY
    Country,
    [Sales_Month]

             
/* ============================================================
   ANALYSIS 13 — SALESPERSON + COUNTRY + PRODUCTIVITY
   ============================================================

   Calculate total revenue and transaction count for each
   salesperson-country combination, then calculate average
   revenue per transaction.

*/
        WITH T1 AS (
    SELECT
        Sales_Person,
        Country,
        SUM(Amount) AS [Total_Revenue],
        COUNT(*) AS [Transaction_Count]
    FROM ChocSales
    GROUP BY
        Sales_Person,
        Country
)

SELECT
    *,
    [Total_Revenue] * 1.0 / [Transaction_Count]
        AS [Revenue_Per_Transaction]
FROM T1
ORDER BY
    [Revenue_Per_Transaction] DESC

/* ============================================================
   ANALYSIS 14 — PRODUCT + COUNTRY + REVENUE EFFICIENCY
   ============================================================

   Calculate revenue per box for each Product-Country
   combination.

*/
      WITH T1 AS (
    SELECT
        Country,
        Product,
        SUM(Amount) AS [Total_Revenue],
        SUM(Boxes_Shipped) AS [Total_Boxes]
    FROM ChocSales
    GROUP BY
        Country,
        Product
)

SELECT
    *,
    [Total_Revenue] * 1.0 / [Total_Boxes] AS [Revenue_Per_Box]
FROM T1
ORDER BY
    [Revenue_Per_Box] DESC;


/* ============================================================
   ANALYSIS 15 — SALESPERSON + COUNTRY + PRODUCT
                   PERFORMANCE SCORECARD
   ============================================================

   Which salesperson-product-market combinations are the
   strongest overall?

*/
   WITH T1 AS (
    SELECT
        Sales_Person,
        Country,
        Product,
        SUM(Amount) AS Total_Revenue,
        SUM(Boxes_Shipped) AS Total_Boxes,
        COUNT(*) AS Total_Transactions
    FROM ChocSales
    GROUP BY
        Sales_Person,
        Country,
        Product
)

SELECT *,
    Total_Revenue * 1.0 / Total_Boxes
        AS Revenue_Per_Box,
    Total_Revenue * 1.0 / Total_Transactions
        AS Revenue_Per_Transaction
FROM T1
ORDER BY
    Total_Revenue DESC;
    


